### PR TITLE
Update Transaction Service endpoint in Safe Service Client tests

### PR DESCRIPTION
**Pull request by germartinez**
## Problem
Since the Transaction Service Staging is used as a backup for Prod, pending transactions created using https://safe-team.staging.gnosisdev.com/ are only stored in Prod

## Solution
Use the Transaction Service Prod (Rinkeby) endpoint for the CI tests in the Safe Service Client

### CODE REVIEW

**Review by iamacook — APPROVED** [review]
💪

**Review by katspaugh — COMMENTED** [review]
Not sure I understand the underlying problem.
Why do we need to use the prod service in e2e tests?

**Comment by germartinez** [comment]
@katspaugh there is no way to get pending transactions from staging.
This Safe has 1 pending transaction and 2 executed transactions: https://safe-team.staging.gnosisdev.com/app/rin:0x4ED1c9E633dcDB0E38f0Fd19Cef03D2C084AbB73/transactions/queue

Prod shows 3 transcations (1 pending + 2 executed):
https://safe-transaction.rinkeby.gnosis.io/api/v1/safes/0x4ED1c9E633dcDB0E38f0Fd19Cef03D2C084AbB73/all-transactions/

Staging shows 2 transactions (2 executed):
https://safe-transaction.staging.gnosisdev.com/api/v1/safes/0x4ED1c9E633dcDB0E38f0Fd19Cef03D2C084AbB73/all-transactions/

**Comment by katspaugh** [comment]
Oh, that makes a lot of sense. On staging thee queue is always empty, and I thought it was a bug.

**Review by katspaugh — APPROVED** [review]

**Pull request merged**
