### PR TITLE
fixed missing required gas field in web3adapter tx calls

### PR DESCRIPTION
**Pull request by vigan-abd**
## What it solves
Resolves issue https://github.com/gnosis/safe-core-sdk/issues/132

## How this PR fixes it

- It adds missing gas property to send transactions in web3 where it's missing
- replaces reading first event with appropriate `ProxyCreation` event

### CODE REVIEW

**Comment by vigan-abd** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vigan-abd** [comment]
hmm I see this error on v1.3.0 tests
```
Error: cannot override "gas" (operation="overrides", overrides=["gas"], code=UNSUPPORTED_OPERATION, version=contracts/5.5.0)
```
could you explain how you're setting gas here? In my issue https://github.com/gnosis/safe-core-sdk/issues/132 I've used official web3 package and it was failing due to missing `gas` field

**Comment by vigan-abd** [comment]
> hmm I see this error on v1.3.0 tests
> 
> ```
> Error: cannot override "gas" (operation="overrides", overrides=["gas"], code=UNSUPPORTED_OPERATION, version=contracts/5.5.0)
> ```
> 
> could you explain how you're setting gas here? In my issue #132 I've used official web3 package and it was failing due to missing `gas` field

hmm I see that this one is related to ethers lib, not web3 adapter (`export TEST_NETWORK=hardhat && export ETH_LIB=ethers && export SAFE_VERSION=1.3.0 && hardhat deploy && nyc hardhat test`), my only change that could cause this could be https://github.com/gnosis/safe-core-sdk/pull/133/files#diff-f00427b63d57168617d1fc66a3342a6c9b1a01e284b7903cde2de971e243b119R381-R384 which in this case I should add gas in web3 provider
will fix this asap

**Comment by vigan-abd** [comment]
hi @germartinez, could you approve the tests to run again please so we can see if failed v1.3 test is working?

**Comment by vigan-abd** [comment]
thanks @germartinez, I see that just one action fails but that doesn't seem to be related to this PR

**Comment by germartinez** [comment]
Hi @vigan-abd!
I would like to push some changes to your branch.
Would you mind checking the box "Allow edits from maintainers"?

**Comment by vigan-abd** [comment]
Hi @germartinez, it seems that it's already checked
image

**Comment by germartinez** [comment]
Sorry, I merged the base branch of the PR into development, causing this one to be closed automatically.
I'll get your commits and create a new one

**Pull request closed without merging**
