### PR TITLE
fix: correct package name in safe-ethers-adapters

### PR DESCRIPTION
**Pull request by prestwich**
## What it solves
`@gnosis.pm/safe-ethers-adapters` has a peer dependency on `@ethersproject/abstract-providers`, which does not exist. This causes an error on installation

```
> $ npm i @gnosis.pm/safe-ethers-adapters
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @gnosis.pm/safe-ethers-adapters@0.1.0-alpha.6
npm WARN Found: @ethersproject/abstract-providers@undefined
npm WARN node_modules/@ethersproject/abstract-providers
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @ethersproject/abstract-providers@"^5.0.0" from @gnosis.pm/safe-ethers-adapters@0.1.0-alpha.6
npm WARN node_modules/@gnosis.pm/safe-ethers-adapters
npm WARN   @gnosis.pm/safe-ethers-adapters@"*" from the root project
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@ethersproject%2fabstract-providers - Not found
npm ERR! 404 
npm ERR! 404  '@ethersproject/abstract-providers@^5.0.0' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

## How this PR fixes it

Corrects the package name in package.json.
This will require republishing the package

### CODE REVIEW

**Comment by prestwich** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by prestwich** [comment]
recheckcla

**Comment by prestwich** [comment]
signing away the rights to a 1-character deletion lmao

**Comment by germartinez** [comment]
Thank you, @prestwich!

The rights have been granted :smile:

**Review by germartinez — APPROVED** [review]

**Pull request merged**
