### PR TITLE
Added safeService.getAllTransactions()

### LINKED ISSUE #111: Add /all-transactions to safe-service-client
## Context / issue

There appears to be no support for all the `GET ​/safes​/{address}​/all-transactions​/` endpoint outlined in the [swagger](https://safe-transaction.gnosis.io/)

## Proposed solution

Add a `safeService.getAllTransactions(safeAddress)`  function

## Additional context

It is needed to build functionality similar to the `History` tab seen in the gnosis safe app. Without it, there is no straightforward way to get an overview of the safe

### PR DESCRIPTION
**Pull request by ioloie**
Resolves #111

Adds a `safeService.getAllTransactions(safeAddress, options)` function to the safe-service-client

### CODE REVIEW

**Comment by ioloie** [comment]
I'm not sure why this is failing. It looks like the same issue was fixed in main by #116.

**Comment by germartinez** [comment]
Hi @ioloie, thank you for this PR! I'll check it later today
It looks you need to add the secret `INFURA_KEY` to your repo settings.

**Comment by ioloie** [comment]
@germartinez Thanks, should be successful on the next run now

**Comment by ioloie** [comment]
@germartinez It looks like I don't have permissions to rerun the pipeline.

**Comment by ioloie** [comment]
@germartinez Is there anything I can do to help move this along?

**Review by germartinez — APPROVED** [review]

**Pull request merged**
